config/routes.rb
Rails.application.routes.draw do

  get 'message/create'
  root 'pages#home'

  get 'pages/terms', to: 'pages#terms'
  get 'pages/privacy', to: 'pages#privacy'
  get 'pages/cookies', to: 'pages#cookies'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/contents/:id/checkout/:pricing_type', to: 'contents#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"

  post '/users/edit', to: 'users#update'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: "update_payment"
  post '/settings/payout', to: 'users#update_payout', as: "update_payout"
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :contents do
    member do
      delete :delete_photo
      post :upload_photo
      post :update_content_status
    end
    resources :orders, only: [:create]
  end

  resources :pages do 
    collection do
      get :terms, :privacy, :cookies
    end
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
                get '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
                post '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
              end

  resources :users, only: [:show] do
    member do
      post '/verify_phone' => 'users#verify_phone'
      patch '/update_phone' => 'users#update_phone'
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/content.rb
class Content < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  belongs_to :category
  
  has_many :pricings
  has_many :orders
  has_many :reviews
  has_many :transactions
  has_many_attached :photos
  has_rich_text :description

  accepts_nested_attributes_for :pricings

  scope :active_contents, -> { where(is_active: false) }

  validates :title, presence: { message: 'cannot be blank' }

  def average_rating
    reviews.count == 0 ? 0 : reviews.average(:stars).round(1)
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  protect_from_forgery except: [:upload_photo]
  before_action :authenticate_user!, except: [:show]
  before_action :set_content, except: [:new, :create]
  before_action :is_authorised, only: [:edit, :update, :upload_photo, :delete_photo]
  before_action :set_step, only: [:update, :edit]

  def new
    @content = current_user.contents.build
    @categories = Category.all
  end

  def create

    if !current_user.is_active_creator
      return redirect_to settings_payout_path, alert: "Please add your bank details for payouts."
    end

    @content = current_user.contents.build(content_params)

    if @content.save
      @content.pricings.create(Pricing.pricing_types.values.map{ |x| {pricing_type: x} })
      redirect_to edit_content_path(@content), notice: "Save..."
    else
      redirect_to request.referrer, flash: { error: @content.errors.full_messages }
    end
  end

  def edit
    @categories = Category.all
  end

  def update

    if @step == 2
      content_params[:pricings_attributes].each do |index, pricing|
        if @content.has_single_price && pricing[:pricing_type] != Pricing.pricing_types.key(0)
          next;
        else
          if pricing[:title].blank? || pricing[:description].blank? || pricing[:delivery_time].blank? || pricing[:price].blank?
            return redirect_to request.referrer, flash: {error: "Invalid pricing"}
          end
        end
      end
    end

    if @step == 3 && content_params[:description].blank?
      return redirect_to request.referrer, flash: {error: "Description cannot be blank"}
    end

    if @step == 4 && @content.photos.blank?
      return redirect_to request.referrer, flash: {error: "You don't have any photos"}
    end

    if @step == 5
      @content.pricings.each do |pricing|
        if @content.has_single_price && !pricing.message?
          next;
        else
          if pricing[:title].blank? || pricing[:description].blank? || pricing[:delivery_time].blank? || pricing[:price].blank?
            return redirect_to edit_content_path(@content, step: 2), flash: {error: "Invalid pricing"}
          end
        end
      end

      if @content.description.blank?
        return redirect_to edit_content_path(@content, step: 3), flash: {error: "Description cannot be blank"}
      elsif @content.photos.blank?
        return redirect_to edit_content_path(@content, step: 4), flash: {error: "You don't have any photos"}
      end
    end

    if @content.update(content_params)
      flash[:notice] = "Saved..."
    else
      return redirect_to request.referrer, flash: {error: @content.errors.full_messages}
    end

    if @step < 5
      redirect_to edit_content_path(@content, step: @step + 1)
    else
      redirect_to dashboard_path
    end

  end

  def show
    @categories = Category.all
  end

  def upload_photo
    @content.photos.attach(params[:file])
    render json: { success: true }
  end

  def delete_photo
    @image = ActiveStorage::Attachment.find(params[:photo_id])
    @image.purge
    redirect_to edit_content_path(@content, step: 4)
  end

  def checkout
    subscription = Subscription.find_by_user_id(current_user.id)
    if subscription.present? && subscription.success?
      plan = Stripe::Plan.retrieve(subscription.plan_id)
      @rate =  plan.metadata.commission.to_f/100
    else
      @rate = 20.0/100
    end

    if current_user.stripe_id
      # @stripe_customer = Stripe::Customer.retrieve(current_user.stripe_id)
      @stripe_customer = Stripe::Customer.list_sources(
                            current_user.stripe_id,
                            {object: 'card'},
                          )
      @content = Content.find(params[:id])
      @pricing = @content.pricings.find_by(pricing_type: params[:pricing_type])
    else
      redirect_to settings_payment_path, alert: "Please add your card first"
    end
  end

  def update_content_status
    if @content.update(is_active: !@content.is_active)
      flash[:notice] = 'Saved'
    else
      flash[:notice] = 'Failed to deactive content'
    end
    redirect_to request.referrer
  end

  private

  def set_step
    @step = params[:step].to_i > 0 ? params[:step].to_i : 1
    if @step > 5
      @step = 5
    end
  end

  def set_content
    @content = Content.friendly.find(params[:id])
  end

  def is_authorised
    redirect_to root_path, alert: "You do not have permission" unless current_user.id == @content.user_id
  end

  def content_params
    params.require(:content).permit(:title, :description, :active, :category_id, :has_single_price, 
                                pricings_attributes: [:id, :title, :description, :delivery_time, :price, :pricing_type])
  end

  def should_generate_new_friendly_id?
    title_changed?
    end
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_step1.html.erb
<style>
.step-content{
  font-family: "Nexa Bold", sans-serif;
}
.button{
  font-family: "Nexa Bold", sans-serif;
}
.label{
  font-family: "Nexa Bold", sans-serif;
}
</style>
<div class="step-content <%= 'is-active' if @step == 1 %>"><br>
    <div class="field">
        <label class="label">Category</label>
        <%= f.select(:category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: @content.category_id))%>
    </div>

    <div class="field">
        <label class="label">Service Title</label>
        <%= f.text_area :title, autocomplete: "title", class: "input" %>
    </div>

    <div class="field">
        <label class="checkbox">
            <%= f.check_box :has_single_price, class: "checkbox", onchange: "this.form.submit();" %> Has single price (Mentor only via text message)
        </label>
    </div>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

app/views/contents/_step2.html.erb
<div class="step-content <%= 'is-active' if @step == 2 %>">
    <div class="field">
        <div class="control"><br>
            <div class="columns has-text-centered">

                <%= f.fields_for :pricings, @content.pricings.order(:pricing_type) do |p| %>
                    <div class="column <%= 'is-4 is-offset-4' if @content.has_single_price && p.object.message? %>
                                      <%= 'is-hidden' if @content.has_single_price && !p.object.message? %> ">
                        <label for="" class="label"><%= p.object.pricing_type.capitalize %></label>
                        <%= p.hidden_field :pricing_type %><br>

                        <div class="control">
                            <%= p.text_field :title, placeholder: "Title", class: "input is-radiusless" %>
                        </div>

                        <div class="control">
                            <%= p.text_area :description, placeholder: "Description", class: "textarea is-radiusless" %>
                        </div>

                        <div class="control has-icons-right">
                            <%= p.number_field :delivery_time, placeholder: "Response Time", class: "input is-radiusless", default: 1 %>
                            <span class="icon is-small is-right">days</span>
                        </div>

                        <div class="control has-icons-right">
                            <%= p.number_field :price, placeholder: "Price", class: "input is-radiusless", default: 1 %>
                            <span class="icon is-small is-right">$</span>
                        </div>

                    </div>
                <% end %>

            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

app/views/contents/_step3.html.erb
<div class="step-content <%= 'is-active' if @step == 3 %>"><br>
    <div class="field">
        <label for="" class="label">Description</label>
        <%= f.rich_text_area :description, rows: 50, cols: 50 %>
    </div>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

app/views/contents/_step4.html.erb
<div class="step-content <%= 'is-active' if @step == 4 %>"><br>

    <div class="field">
    <div class="field">
        <label for="" class="label">Pitch Video (Upload to YouTube and provide the unique 11 characters after "v=" from the url.)</label>
        <%= f.text_field :pitch, autocomplete: "video url", class: "input" %>
    </div>
        <label for="" class="label">Photo Gallery</label>
        <div class="control">
            <div class="m-b-20">
                <div class="dropzone" id="myDropzone" action="/contents/<%= @content.id %>/upload_photo"></div>
            </div>

            <div class="columns is-multiline" style: width: 100% %>
                <% @content.photos.each do |photo| %>
                    <div class="column is-one-fifth">
                        <div class="card is-image">
                            <div class="card-image">
                                <%= link_to 'Remove', delete_photo_content_url(photo_id: photo.id, id: @content.id, step: @step), 
                                        method: :delete,
                                        data: { confirm: "Are you sure?" },
                                        class: "delete delete-file is-pulled-right",
                                        style: "z-index: 100"  %>

                                <figure class="image is-4by3">
                                    <%= image_tag url_for(photo) %>
                                </figure>
                            </div>
                        </div>
                    </div>

                <% end %>
            </div>
        </div>
    </div>
</div>

<script>
    Dropzone.options.myDropzone = {
        paramName: "file",
        maxFilesize: 500,
        acceptedFiles: "image/*",
        init: function() {
            this.on('complete', function (file) {
                location.reload();
            })
        }
    }
</script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

app/views/contents/_step5.html.erb
<div class="step-content has-text-centered <%= 'is-active' if @step == 5 %>"><br>
    <div>
        <%= hidden_field_tag 'active', 'true' if @step == 5 %>
        <strong class="is-size-2">Almost there...</strong>
        <p>Let's publish your service and get some audience rolling in.</p>
    </div>
</div>

<div class="field is-grouped is-grouped-centered m-t-25">
    <p class="control <%= 'is-hidden' if @step <= 1 %>">
        <%= link_to 'Back', edit_content_path(@content, step: @step - 1), class: "button is-light" %>
    </p>

    <p class="control">
        <% if @step != 5 %>
            <%= f.submit 'Save & Continue', class: "button is-black" %>
        <% else %>
            <%= link_to 'Publish', content_path(@content.id, content: {active: true}, step: @step), 
                        method: :put, 
                        data: {confirm: "Do you want to publish this content?"},
                        class: "button is-black" %>
        <% end %>
    </p>
</div>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">

app/views/contents/checkout.html.erb
<style>
.column{
    font-family: "Nexa Bold", sans-serif;
}
.title{
    font-family: "Nexa Bold", sans-serif;
}
.media-content{
    font-family: "Nexa Bold", sans-serif;
}
.button{
    font-family: "Nexa Bold", sans-serif;
}
</style>
<% content_for(:html_title) { 'Checkout - Ceefuu' } %>
<section class="section">
    <div class="container">

        <%= form_with model: [@content, @content.orders.new] do |f| %>
            <%= hidden_field_tag 'pricing_type', @pricing.pricing_type %>

            <div class="columns">

                <!-- LEFT SIDE -->
                <div class="column is-two-thirds">
                    <div class="columns is-multiline">
                        <div class="column is-full">
                            <div class="card">
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-5">Payment method</p>
                                    </div>
                                    <hr>
                                    <div class="content">
                                        <% @stripe_customer.data.each do |payment| %>
                                            <div class="control">
                                                <%= radio_button_tag 'payment', payment.id, checked: true %>
                                                <span class="m-l-10">
                                                    <%= payment.brand %> <%= "Card: **** **** **** " + payment.last4 %>
                                                </span>
                                            </div>
                                        <% end %>
                                    </div>
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>


                <!-- RIGHT SIDE -->
                <div class="column">
                    <div class="columns is-multiline">
                        <div class="column is-full">
                            <div class="card">
                                <div class="card-content">
                                    <div class="content">
                                        <p class="title is-5">Summary</p>
                                    </div>
                                    <hr>
                                    <article class="media">
                                        <div class="media-content">
                                            <figure class="image is-4by4">
                                                <%= image_tag content_cover(@content) %>
                                            </figure>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Subtotal
                                        </div>
                                        <div class="media-right">
                                            $<%= '%.2f' % @pricing.price %>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Service fee (<%= (@rate * 100).to_i %>%)
                                        </div>
                                        <div class="media-right">
                                            $<%= '%.2f' % (@pricing.price * @rate) %>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Total
                                        </div>
                                        <div class="media-right">
                                            $<%= '%.2f' % (@pricing.price * (@rate + 1)) %>
                                        </div>
                                    </article>

                                    <article class="media">
                                        <div class="media-content">
                                            Total delivery time
                                        </div>
                                        <div class="media-right">
                                            <%= pluralize(@pricing.delivery_time, 'day') %>
                                        </div>
                                    </article>
                                    
                                    <%= f.submit "Place Your Order", class: "button is-fullwidth is-black", data: {confirm: "Are you sure?"} %>

                                </div>
                            </div>
                        
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</section>

app/views/contents/show.html.erb
<style>
.rounded-img-content{
  display: inline-block;
  width: 96px;
  height: 96px;
  border-radius: 50%;
  overflow: hidden;
}
.rounded-img {
  width: inherit;
  height: inherit;
  border-radius: inherit;
  
  object-fit: cover;
  object-position: center;
}

.video-container {
  position: relative;
  padding-bottom: 56.25%;
  padding-top: 30px;
  height: 0;
  overflow: hidden;
}

.video-container iframe,
.video-container object,
.video-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}

.rounded-img-container {
  display: inline-block;
  width: 128px;
  height: 128px;
  border-radius: 50%;
  overflow: hidden;
}
.title{
    font-family: "Nexa Bold", sans-serif;
}
.tabs{
    font-family: "Nexa Bold", sans-serif;
}
.media-content{
    font-family: "Nexa Regular", sans-serif;
}
.m-t-30{
    font-family: "Nexa Regular", sans-serif;
}
.button{
    font-family: "Nexa Bold", sans-serif;
}
.media-right{
    font-family: "Nexa Bold", sans-serif;
}
</style>
<% content_for(:html_title) {@content.title}%><% content_for(:html_title) { ' - Ceefuu' } %>

<% content_for :head do %>
  <meta name="turbolinks-cache-control" content="no-cache">
    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.ceefuu.com/">
    <meta property="og:title" content="<%= @content.title %>">
    <meta property="og:image" content="<%= image_url("ceefuu-og.png") %>">


    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://www.ceefuu.com/">
    <meta property="twitter:title" content="<%= @content.title %>">
    <meta property="twitter:image" content="<%= image_url("ceefuu-og.png") %>">
<% end %>



<section class="section">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <div class="columns is-multiline">

                    <!-- Carousel -->
                    <div class="column is-full">   
                        <div class="card">
                            <div class="card-content">
                                <div class="content">
                                    <p class="title is-4"><%= @content.title %></p>
                                </div>
                                <hr>
                                <div class="carousel" id="carousel-photo">
                                    <% @content.photos.each do |photo| %>
                                        <div class="carousel-item has-background image is-5by3">
                                            <%= image_tag url_for(photo), class: "is-background", width: "100%" %>
                                        </div>
                                    <% end %>
                                    <% if @content.pitch.present? %>
                                        <div class="video-container">
                                            <iframe src="https://www.youtube.com/embed/<%= @content.pitch %>" allowfullscreen></iframe>
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- About Section -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content">
                                <article class="media">
                                    <div class="media-content">
                                        <%= @content.description %>
                                    </div>
                                </article>
                            </div>
                        </div>                        
                    </div>
                    
                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Pricing Section -->
                    <div class="column is-full">

                        <div class="tabs is-fullwidth" id="tabs">
                            <ul>
                                <% Pricing.pricing_types.each do |key, value| %>
                                    <li class="tab <%= 'is-active' if value == 0 %> " 
                                                data-tab="<%= key %>" style="<%= 'display: none' if @content.has_single_price && value != 0 %>">
                                        <a><%= key.capitalize %></a>
                                    </li>
                                <% end %>
                            </ul>
                        </div>

                        <div class="tabs-content">

                            <% @content.pricings.each do |p| %>
                                <div class="tab-content" id="tab-<%= p.pricing_type %>" style="<%= 'display: none' if !p.message? %>">
                                    <div class="card">
                                        <div class="card-content">
                                            <div class="media">
                                                <div class="media-content">
                                                    <strong><%= p.title %></strong>                                                                                                        
                                                </div>
                                                <div class="media-right">
                                                    <p class="title is-4"><%= number_to_currency(p.price) %></p>
                                                </div>                                                
                                            </div>
                                            <div class="content f-15">
                                                <p class="m-t-30"><%= p.description %></p>
                                                <p class="m-t-30">
                                                    <strong><i class="far fa-clock"></i> <%= pluralize(p.delivery_time, 'Day') %> -  Response Time</strong>                                                    
                                                </p>
                                            </div>
                                            <% if (!user_signed_in? && @content.active) || (user_signed_in? && @content.active && @content.user_id != current_user.id) %>
                                                <%= link_to "Continue (#{number_to_currency(p.price)})", checkout_path(id: @content.id, pricing_type: p.pricing_type), class: "button is-fullwidth is-black" %>
                                            <% else %>
                                                <button class="button is-fullwidth is-black" disabled>Not Available</button>  
                                            <% end %>
                                            
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                        </div>

                    </div>

                    <!-- Profile Section -->
                    <div class="column">
                        <div class="card">
                            <div class="card-content is-horizontal-center is-flex">
                                <%= link_to users_path(@content.user) do %>
                                    <div class="rounded-img-content">
                                        <%= image_tag avatar_url(@content.user), class: "rounded-img" %>
                                    </div>
                                <% end %>
                            </div>
                            <div class="card-content f-15">
                                <div class="content has-text-centered">
                                <%= link_to users_path(@content.user) do  %>
                                  <p class="title is-5"><%= @content.user.full_name %></p> 
                                <% end %> 
                            </div><br/>
                            
                                <article class="media">
                                    <div class="media-content">
                                        <i class="fas fa-map-marker-alt m-r-5"></i> From
                                    </div>
                                    <div class="media-right">
                                        <%= @content.user.from %>
                                    </div>
                                </article>
                                <article class="media">
                                    <div class="media-content">
                                        <%= @content.user.about %>
                                    </div>
                                </article>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>
<%= render "shared/footer" %>

<script>
    BulmaCarousel.attach('#carousel-photo', {
        slidesToScroll: 1,
        slidesToShow: 1
    });

    $(document).ready(function() {
        $('#tabs li').on('click', function() {
            var type = $(this).data('tab');

            $('#tabs li').removeClass('is-active');
            $(this).addClass('is-active');

            $('.tab-content').hide();
            $('#tab-' + type).show();
        }) 
    })

</script>