config/routes.rb
Rails.application.routes.draw do

  get 'message/create'
  root 'pages#home'

  get 'pages/terms', to: 'pages#terms'
  get 'pages/privacy', to: 'pages#privacy'
  get 'pages/cookies', to: 'pages#cookies'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/contents/:id/checkout/:pricing_type', to: 'contents#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"

  post '/users/edit', to: 'users#update'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: "update_payment"
  post '/settings/payout', to: 'users#update_payout', as: "update_payout"
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :contents do
    member do
      delete :delete_photo
      post :upload_photo
      post :update_content_status
    end
    resources :orders, only: [:create]
  end

  resources :pages do 
    collection do
      get :terms, :privacy, :cookies
    end
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
                get '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
                post '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
              end

  resources :users, only: [:show] do
    member do
      post '/verify_phone' => 'users#verify_phone'
      patch '/update_phone' => 'users#update_phone'
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  extend FriendlyId
  friendly_id :username, use: :slugged
  has_one_attached :avatar
  has_many :contents

  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "creator_id", class_name: "Order"

  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :confirmable, omniauth_providers: [:stripe_connect,:facebook]

  validates :full_name, presence: true, length: {maximum: 50}
  validates :username, uniqueness: true, if: -> { username.present? }
  validates :terms_of_service, acceptance: true

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image

        user.uid = auth.uid
        user.provider = auth.provider

      end
    end
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
  def is_active_creator
    !self.merchant_id.blank?
  end
end
#   def generate_pin
#     self.pin = SecureRandom.hex(2)
#     self.phone_verified = false
#     save
#   end

#   def send_pin
#     @client = Twilio::REST::Client.new
#     @client.messages.create(
#       from: '+15034043616',
#       to: self.phone,
#       body: "Your Ceefuu pin is #{self.pin}"
#     )
#   end

#   def verify_pin(entered_pin)
#     update(phone_verified: true) if self.pin == entered_pin
#   end
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
    @subscription = Subscription.find_by_user_id(current_user.id)
    if @subscription.present?
      @plan = Stripe::Plan.retrieve(@subscription.plan_id)
    end
  end

  def show
    @user = User.friendly.find(params[:id])
    @reviews = Review.where(creator_id: @user.id).order("created_at desc")
  end

  def update
    @user = current_user
    if @user.update(current_user_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot update..."
    end
    redirect_to dashboard_path
  end

  # def update_phone
  #   current_user.update_attributes(user_params)
  #   current_user.generate_pin
  #   current_user.send_pin

  #   redirect_to edit_user_registration_path, notice: "Saved..."
  # rescue Exception => e
  #   redirect_to edit_user_registration_path, alert: "#{e.message}"
  # end

  # def verify_phone
  #   current_user.verify_pin(params[:user][:pin])

  #   if current_user.phone_verified
  #     flash[:notice] = "Your phone number is verified."
  #   else
  #     flash[:alert] = "Cannot verify your phone number."
  #   end

  #   redirect_to edit_user_registration_path

  # rescue Exception => e
  #   redirect_to edit_user_registration_path, alert: "#{e.message}"
  # end

  def update_payment
    if !current_user.stripe_id
      customer = Stripe::Customer.create(
        email: current_user.email,
        name: current_user.full_name,
        source: params[:stripeToken]
      )
    else
      customer = Stripe::Customer.update(
        current_user.stripe_id,
        source: params[:stripeToken]
      )
    end

    if current_user.update(stripe_id: customer.id)
      flash[:notice] = "New card is saved"
    else
      flash[:alert] = "Invalid card"
    end
    redirect_to request.referrer
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to request.referrer
  end

  def update_payout
    if !current_user.merchant_id.blank?
      account = Stripe::Account.retrieve(current_user.merchant_id)
      @login_link = account.login_links.create()
    else
      flash[:alert] = "Add a Stripe account to recieve payments."
    end
    redirect_to request.referrer
  end

  def earnings
    @net_income = (Transaction.where("creator_id = ?", current_user.id).sum(:amount)).round(2)

    # @withdrawn = Transaction.where("buyer_id = ? AND status = ? AND transaction_type = ?",
    #                 current_user.id,
    #                 Transaction.statuses[:approved],
    #                 Transaction.transaction_types[:withdraw]
    #             ).sum(:amount)
    
    # @pending = Transaction.where("buyer_id = ? AND status = ? AND transaction_type = ?",
    #             current_user.id,
    #             Transaction.statuses[:pending],
    #             Transaction.transaction_types[:withdraw]
    #             ).sum(:amount)

    # @purchased = Transaction.where("buyer_id = ? AND source_type = ? AND transaction_type = ?",
    #             current_user.id,
    #             Transaction.source_types[:system],
    #             Transaction.transaction_types[:trans]
    #             ).sum(:amount)

    # @withdrawable = current_user.wallet

    @transactions = Transaction.where("creator_id = ? OR (buyer_id = ? AND source_type = ?)",
                    current_user.id,
                    current_user.id,
                    Transaction.source_types[:system]
                  ).page(params[:page]).order("created_at DESC")
  end

  # def withdraw
  #   amount = params[:amount].to_i
  #   is_pending_withdraw = Transaction.exists?(buyer_id: current_user.id, 
  #                                             status: Transaction.statuses[:pending],
  #                                             transaction_type: Transaction.transaction_types[:withdraw])
    
  #   if amount <= 0
  #     flash[:alert] = "Invalid amount"
  #   elsif amount > current_user.wallet
  #     flash[:alert] = "You're asking for more than you have"
  #   elsif !is_pending_withdraw.blank?
  #     flash[:alert] = "You currently have a pending withdraw request"
  #   else
  #     transaction = Transaction.new
  #     transaction.status = Transaction.statuses[:pending]
  #     transaction.transaction_type = Transaction.transaction_types[:withdraw]
  #     transaction.source_type = Transaction.source_types[:system]
  #     transaction.buyer = current_user
  #     transaction.amount = amount

  #     if transaction.save
  #       flash[:notice] = "Create withdraw request successfully"
  #     else
  #       flash[:alert] = "Cannot create a request"
  #     end
  #   end

  #   redirect_to request.referrer
  # end

  def remove_subscription
    @subscription = Subscription.find_by_user_id(current_user.id)

    if @subscription.present? && @subscription.sub_id
      Stripe::Subscription.delete(@subscription.sub_id)
      return redirect_to request.referrer, notice: "Your subscription is cancelled"
    end
    return redirect_to request.referrer, aler: "Cannot cancel your subscription. Contact admin."
  end

  def payment
    if current_user.stripe_id.present?
      payment_cards = Stripe::Customer.list_sources(
                        current_user.stripe_id,
                        {object: 'card'},
                      )
      @card_detail = payment_cards.data.first
    end
  end

  def payout
    if !current_user.merchant_id.blank?
      account = Stripe::Account.retrieve(current_user.merchant_id)
      @login_link = account.login_links.create()
    else
      flash[:alert] = "Add a Stripe account to recieve payments"
    end
  end

  private
  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<style>
.button{
    font-family: "Nexa Bold", sans-serif;
}
</style>
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "button is-black is-outlined is-fullwidth" %>
<% end %>

app/views/users/_unfollow.html.erb
<style>
.button{
    font-family: "Nexa Bold", sans-serif;
}
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Following", class: "button is-black is-outlined is-fullwidth" %>
<% end %>

app/views/users/dashboard.html.erb
<style>
.ellipsis {
  display: block;
  /* Fallback for non-webkit */
  display: -webkit-box;
  /*   max-width: 400px; */
  /*   height: 109.2px; */
  /* Fallback for non-webkit */
  margin: 0 auto;
  /*   font-size: 26px; */
  line-height: 1.4;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}

.is-ellipsis-2 {
  -webkit-line-clamp: 1;
}

.rounded-img-container {
  display: inline-block;
  width: 128px;
  height: 128px;
  border-radius: 50%;
  overflow: hidden;
}
.rounded-img {
  width: inherit;
  height: inherit;
  border-radius: inherit;
  
  object-fit: cover;
  object-position: center;
}
.button{
    font-family: "Nexa Bold", sans-serif;
}
.title{
    font-family: "Nexa Bold", sans-serif;
}
.media{
    font-family: "Nexa Bold", sans-serif;
}
.column{
    font-family: "Nexa Regular", sans-serif;
}
.has-text-left{
    font-family: "Nexa Regular", sans-serif;
}
</style>
<% content_for(:html_title) { 'Dashboard - Ceefuu' } %>
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                                <div class="rounded-img-container">
                                    <%= image_tag avatar_url(current_user), class: "rounded-img" %>
                                </div>
                            </div>
                            
                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= current_user.full_name %></p>
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post do |f| %>
                                        <div class="file">
                                            <label class="button is-black is-outlined is-fullwidth">
                                                <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit();" %>
                                                <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp; Upload Avatar
                                            </label>
                                        </div>
                                    <% end %>
                                </div>
                                <hr class="h-10">
                                
                                <!-- From -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Location</div>
                                        <div class="media-right">
                                            <strong><%= current_user.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-from', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :from, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-from">Cancel</a>
                                            <%= f.submit "Save", class: "button is-black" %>
                                        <% end %>
                                    </div>

                                </article>
                                
                                <!-- Subscription -->
                                <% if @subscription.present? %>
                                    <hr class="h-10">
                                    <article>
                                        <div class="media">
                                            <div class="media-content">Subscription</div>
                                            <div class="media-right">
                                                <strong><% if @plan %> <%= @plan.nickname %> <% end %></strong> <i class="toggle far fa-edit" aria-controls="user-subscription"></i>
                                            </div>
                                        </div>

                                        <div class="content">
                                            <%= form_with url: remove_subscription_path, method: :delete, html: { id: 'user-subscription', class: 'is-hidden' } do |f| %>
                                                <small>Expire at: <%= @subscription.expired_at %></small>                 
                                                <%= f.submit "Cancel My Subscription", class: "button is-danger is-fullwidth m-t-20" %>
                                            <% end %>
                                        </div>
                                    </article>
                                <% end %>
                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="has-text-left">
                                                <strong>Bio</strong>
                                                <br>
                                                <%= current_user.about %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-about"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-about', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_area :about, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-about">Cancel</a>
                                            <%= f.submit "Save", class: "button is-black" %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Language -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p class="has-text-left">
                                                <strong>Language</strong>
                                                <br>
                                                <%= current_user.language %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-language"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id: 'user-language', class: 'is-hidden'} do |f| %>
                                            <div class="field">
                                                <%= f.text_field :language, autofocus: true, autocomplete: 'form', class: 'input'%>
                                            </div>
                                            <a class="toggle button is-light" aria-controls="user-language">Cancel</a>
                                            <%= f.submit "Save", class: "button is-black" %>
                                        <% end %>
                                    </div>

                                </article>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Create New Content -->
                    <div class="column is-one-third has-text-centered">
                        <%= link_to new_content_path do %>
                            <div class="card">

                                <div class="card-image card-content is-horizontal-center is-flex ">
                                    <figure class="image is-128x128 ">
                                        <%= image_tag 'icon_add.png' %>
                                    </figure>
                                </div>

                                <div class="card-content">
                                    <strong>Add New Service</strong>
                                </div>    

                            </div>
                        <% end %>
                    </div>


                    <!-- Content -->
                    <% current_user.contents.each do |content| %>

                        <div class="column is-one-third">
                            <div class="card">

                                <div class="card-image">
                                    <%= link_to edit_content_path(content) do %>
                                        <figure class="image is-5by3">
                                            <%= image_tag content_cover(content) %>
                                        </figure>
                                    <% end %>
                                </div>

                                <div class="card-content p-t-3 p-b-3">
                                    <p class="subtitle is-6 m-b-5 ellipsis is-ellipsis-2"><%= link_to content.title, content_path(content), class: "has-text-black" %></p>                                       
                                </div>

                        <footer class="card-footer">
                                <span class="card-footer-item">
                                    <%= link_to edit_content_path(content) do %>
                                        <small class="has-text-black">
                                            Edit&nbsp;
                                        </small>
                                    <% end %>
                                </span>
                                <span class="card-footer-item">
                                    <%= link_to update_content_status_content_path(content), method: :post do %>
                                        <small class="has-text-black">
                                         <%= content.is_active ? 'Activate' : 'Deactivate' %>
                                        </small>
                                    <% end %>
                                </span>
                        </footer>  
                                
                            </div>
                        </div>

                    <% end %>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>
<%= render "shared/footer" %>
<script>
$(document).ready(function(){
    $('.toggle').on('click', (e) => {
        e.stopPropagation();
        e.preventDefault();
        $('#' + e.target.getAttribute('aria-controls')).toggleClass('is-hidden');
    })
})
</script>

app/views/users/payment.html.erb
<style>
/**
 * The CSS shown here will not be introduced in the Quickstart guide, but shows
 * how you can use CSS to style your Element's container.
 */
.StripeElement {
  box-sizing: border-box;

  height: 40px;

  padding: 10px 12px;

  border: 1px solid transparent;
  border-radius: 4px;
  background-color: white;

  box-shadow: 0 1px 3px 0 #e6ebf1;
  -webkit-transition: box-shadow 150ms ease;
  transition: box-shadow 150ms ease;
}

.StripeElement--focus {
  box-shadow: 0 1px 3px 0 #cfd7df;
}

.StripeElement--invalid {
  border-color: #fa755a;
}

.StripeElement--webkit-autofill {
  background-color: #fefde5 !important;
}

.title {
  font-family: "Nexa Bold", sans-serif;
}
.button{
  font-family: "Nexa Bold", sans-serif;
}
</style>
<% content_for(:html_title) { 'Add Payment Details - Ceefuu' } %>
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8-tablet is-6-desktop is-6-widescreen">
                <p class="title has-text-centered">Payment Method</p>
                <% if @card_detail.present? %>
                  <div class="card">
                      <div class="card-header-title is-centered">
                        <%= @card_detail.brand %> <%= "Card: **** **** **** " + @card_detail.last4 %>
                      </div>
                  </div>
                <% end %>

                <%= form_with url: update_payment_path, local: true, id: "payment-form" do |f| %>
                    <div class="card form-row">
                        <div id="card-element">
                        <!-- A Stripe Element will be inserted here. -->
                        </div>

                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>
                    <div class="field is-grouped is-grouped-centered">
                        <%= f.submit "#{current_user.stripe_id ? "Update Card" : "Add Credit Card"}", 
                                        class: "button is-black m-t-20" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</section>

<script>

    // Create a Stripe client.
    var stripe = Stripe('<%= Rails.application.credentials[:stripe][:public_key] %>');


    // Create an instance of Elements.
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    // (Note that this demo uses a wider set of styles than the guide below.)
    var style = {
        base: {
            color: '#32325d',
            fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
            fontSmoothing: 'antialiased',
            fontSize: '16px',
            '::placeholder': {
            color: '#aab7c4'
            }
        },
        invalid: {
            color: '#fa755a',
            iconColor: '#fa755a'
        }
    };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
            displayError.textContent = event.error.message;
        } else {
            displayError.textContent = '';
        }
    });

    // Handle form submission.
    var form = document.getElementById('payment-form');
        form.addEventListener('submit', function(event) {
        event.preventDefault();

        stripe.createToken(card).then(function(result) {
            if (result.error) {
            // Inform the user if there was an error.
            var errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;
            } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
            }
        });
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
        // Insert the token ID into the form so it gets submitted to the server
        var form = document.getElementById('payment-form');
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        form.appendChild(hiddenInput);

        // Submit the form
        form.submit();
        }
</script>

app/views/users/payout.html.erb
<style>
.title {
  font-family: "Nexa Bold", sans-serif;
}
.button{
  font-family: "Nexa Bold", sans-serif;
}
.is-size-7{
    font-family: "Nexa Regular", sans-serif;
}
</style>
<% content_for(:html_title) { 'Add Payout Method - Ceefuu' } %>
<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8-tablet is-6-desktop is-6-widescreen">
                <p class="title has-text-centered">Receive your earnings</p>
                
                <p class="is-size-7 has-text-centered">(***Before listing your service, kindly connect your bank account via Stripe to recieve payouts***)<p>
               
                <br>
            <div class="field is-grouped is-grouped-centered">
                <% if current_user.merchant_id.blank? %>
                    <%= link_to "Connect with Stripe", stripe_express_path, class: "button is-black" %>
                <% else %>
                <br/>
                <div class="text-center">
                    <%= link_to "Earnings Dashboard", @login_link&.url, class: "button is-black" %>
                </div>
                <% end %> 
            </div>
            </div>
        </div>
    </div>
</section>