config/routes.rb
Rails.application.routes.draw do

  get 'message/create'
  root 'pages#home'

  get 'pages/terms', to: 'pages#terms'
  get 'pages/privacy', to: 'pages#privacy'
  get 'pages/cookies', to: 'pages#cookies'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/contents/:id/checkout/:pricing_type', to: 'contents#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"

  post '/users/edit', to: 'users#update'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: "update_payment"
  post '/settings/payout', to: 'users#update_payout', as: "update_payout"
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :contents do
    member do
      delete :delete_photo
      post :upload_photo
      post :update_content_status
    end
    resources :orders, only: [:create]
  end

  resources :pages do 
    collection do
      get :terms, :privacy, :cookies
    end
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
                get '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
                post '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
              end

  resources :users, only: [:show] do
    member do
      post '/verify_phone' => 'users#verify_phone'
      patch '/update_phone' => 'users#update_phone'
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_categories.html.erb
<style>

div.scrollmenu {
  background-color: #ffffff;
  overflow: auto;
  white-space: nowrap;
  -webkit-overflow-scrolling: touch;
  -ms-overflow-style: -ms-autohiding-scrollbar;
}

div.scrollmenu::-webkit-scrollbar {
  display: none; }

div.scrollmenu a {
  display: inline-block;
  color: black;
  text-align: center;
  padding: 16px;
  text-decoration: none;
}

div.scrollmenu a:hover {
  background-color: #ffffff;
}

</style>
 
<nav class="navbar has-shadow" style="z-index: 5">
    <div class="container">
        <div class="scrollmenu">
            <% @categories.each do |item| %>
              <%= link_to "#{item.name}", search_path(category: item.id), class: "navbar-item" %>
            <% end %>
        </div>
    </div>
</nav>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

app/views/shared/_contents.html.erb
<style>
.ellipsis {
  display: block;
  /* Fallback for non-webkit */
  display: -webkit-box;
  /*   max-width: 400px; */
  /*   height: 109.2px; */
  /* Fallback for non-webkit */
  margin: 0 auto;
  /*   font-size: 26px; */
  line-height: 1.4;
  -webkit-box-orient: vertical;
  overflow: hidden;
  text-overflow: ellipsis;
}

.rounded-img-page{
  display: inline-block;
  width: 32px;
  height: 32px;
  border-radius: 50%;
  overflow: hidden;
}
.rounded-img {
  width: inherit;
  height: inherit;
  border-radius: inherit;
  
  object-fit: cover;
  object-position: center;
}

.is-ellipsis-2 {
  -webkit-line-clamp: 1;
}

/* Flexible iFrame */

.flexible-container {
  position: relative;
  padding-bottom: 56.25%;
  padding-top: 30px;
  height: 0;
  overflow: hidden;
}

.flexible-container iframe,
.flexible-container object,
.flexible-container embed {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
}
.subtitle{
    font-family: "Nexa Bold", sans-serif;
}
</style>

<% @contents.each do |content| %>
    <div class="column is-one-third">
        <div class="card">

            <div class="card-image">
                <%#= link_to content_path(content) do %>
                    <!-- <figure class="image is-4by4">
                        <%= image_tag content_cover(content) %>
                    </figure> -->
                    <div class="column is-full">   
                        <div class="card">
                           <figure class="image is-5by3">
                                <%= image_tag content_cover(content) %>
                           </figure>
                        </div>
                    </div>
            </div>

            <div class="card-content p-t-5 p-b-5">
                <p class="subtitle is-6 m-b-5 ellipsis is-ellipsis-2"><%= link_to content.title, content_path(content), class: "has-text-black" %></p>
                <span class="star-review"><i class="fa fa-star"></i>
                    <%= content.average_rating %>
                    <span class="has-text-black">(<%= content.reviews.count %>)</span>
                </span>                                        
            </div>

            <footer class="card-footer">
                <span class="card-footer-item">
                    <%= link_to users_path(content.user) do %>
                        <div class="rounded-img-page">
                            <%= image_tag avatar_url(content.user), class: "rounded-img" %>
                        </div>
                    <% end %>
                </span>

                <a class="has-text-black is-block card-footer-item has-text-centered">
                    <span class="small-title">STARTING AT</span> 
                    <strong><%= number_to_currency(content.price) %></strong>
                </a>
            </footer>  
            
        </div>
    </div>

<% end %>
<script>
    BulmaCarousel.attach('#carousel-photo', {
        slidesToScroll: 1,
        slidesToShow: 1
    });

    $(document).ready(function() {
        $('#tabs li').on('click', function() {
            var type = $(this).data('tab');

            $('#tabs li').removeClass('is-active');
            $(this).addClass('is-active');

            $('.tab-content').hide();
            $('#tab-' + type).show();
        }) 
    })

</script>

app/views/shared/_footer.html.erb
    <style>
    
    .footer.footer-left {
    padding-top: 3rem;
    padding-bottom: 3rem;
}

    .footer {
    background-color: #fafafa;
    padding: 3rem 1.5rem 6rem;
}

    .px-2{padding-left:.5rem !important;padding-right:.5rem !important}
    .py-2{padding-top:.5rem !important;padding-bottom:.5rem !important}
    .columns.is-vcentered{-webkit-box-align:center;-ms-flex-align:center;align-items:center}
    .inline-block {display: inline-block;}

    .footer .footer-link {
    color: #000000;
    -webkit-transition: color .3s;
    transition: color .3s;
}

@media only screen and (min-width: 768px) and (max-width: 1024px) and (orientation: portrait)

{
.d-column-tablet-p {
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
}
}

.is-align-items-center {
    -webkit-box-align: center !important;
    -ms-flex-align: center !important;
    align-items: center !important;
}

@media only screen and (max-width: 767px){
.d-column-mobile {
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -ms-flex-direction: column;
    flex-direction: column;
}
}
.subtitle{
    font-family: "Nexa Bold", sans-serif;
}
.inline-block{
    font-family: "Nexa Bold", sans-serif;
}
</style>
    
    <footer class="footer footer-left">
        <div class="container">
            <div class="columns is-vcentered">
                <div class="column is-8">
                    <div class="is-flex d-column-mobile d-column-tablet-p is-align-items-center">
                        <ul class="py-2">
                            <li class="inline-block px-2">
                                <%= link_to 'Terms', terms_pages_path, class: "footer-link"  %>
                            </li>
                            <li class="inline-block px-2">
                                <%= link_to 'Privacy', privacy_pages_path, class: "footer-link"  %>
                            </li>
                            <li class="inline-block px-2">
                                <%= link_to 'Cookies', cookies_pages_path, class: "footer-link"  %>
                            </li>
                            <li class="inline-block px-2">
                        </ul>
                    </div>
                </div>
                <div class="column is-4 has-text-right has-text-centered-mobile">
                    <p class="subtitle footer-text has-text-black medium:text-right is-6" data-config-id="copyright">&copy; 2022 Ceefuu, Inc.</p>
                </div>
            </div>
        </div>
    </footer>

app/views/shared/_navbar.html.erb
<style>

div.scrollmenu {
  background-color: #ffffff;
  overflow: auto;
  white-space: nowrap;
}

div.scrollmenu a {
  display: inline-block;
  color: black;
  text-align: center;
  padding: 16px;
  text-decoration: none;
}

div.scrollmenu a:hover {
  background-color: #ffffff;
}

.navbar-end{
    font-family: "Nexa Bold", sans-serif;
}

.scrollmenu{
    font-family: "Nexa Bold", sans-serif;
}

.input{

    width: 500px
}
</style>

<nav class="navbar is-transparent has-shadow" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item has-text-weight-bold" href="/">
            <%= image_tag "home/logo.png", width: "70%", height: "70%" %>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="true" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>

    </div>



    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-end">
         <div class="navbar-item">
            <%= link_to 'Discover', search_path, class: "navbar-item" %>
            <a href = "mailto: support@ceefuu.com" target="_newtab" class="navbar-item" >Help</a>
        </div>

            <% if (!user_signed_in?) %>
                <div class="navbar-item">
                    <div class="buttons">
                        <%= link_to  "Sign in", new_user_session_path, class: "button is-light", data: { turbolinks: false } %>
                        <%= link_to  "Sign up", new_user_registration_path, class: "button is-black" %>
                    </div>
                </div>
            <% else %>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link"> 
                        <%= current_user.full_name %>
                    </a>

                    <div class="navbar-dropdown is-hidden-mobile is-boxed">
                        <%= link_to "Profile", current_user, class: "navbar-item" %>
                        <%= link_to "Settings", edit_user_registration_path, class: "navbar-item" %>
                        <%= link_to 'Dashboard', dashboard_path, class: "navbar-item" %>
                        <hr class="navbar-divider">
                        <%= link_to  "Log out", destroy_user_session_path, method: :delete, class: "navbar-item" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</nav>

<% if (user_signed_in?) && !current_page?(root_path) && !current_page?(plans_path) && !current_page?(search_path) && !current_page?("/contents/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
    <nav class="navbar has-shadow" style="z-index: 5">
        <div class="container">
            <div class="scrollmenu">
                <%= link_to 'Home', dashboard_path, class: "navbar-item" %>
                <%= link_to 'Add New Service', new_content_path, class: "navbar-item" %>
                <%= link_to 'Sales History', selling_orders_path, class: "navbar-item" %>
                <%= link_to 'Purchase History', buying_orders_path, class: "navbar-item" %>
                <%= link_to 'Earnings', earnings_path, class: "navbar-item" %>
                <%= link_to 'Payment Method', settings_payment_path, class: "navbar-item" %>
                <%= link_to 'Payout Method', settings_payout_path, class: "navbar-item" %>
            </div>
        </div>
    </nav>
<% end %>


<script>
document.addEventListener('DOMContentLoaded', function () {

  // Get all "navbar-burger" elements
  var $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach(function ($el) {
      $el.addEventListener('click', function () {

        // Get the target from the "data-target" attribute
        var target = $el.dataset.target;
        var $target = document.getElementById(target);

        // Toggle the class on both the "navbar-burger" and the "navbar-menu"
        $el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});

document.querySelectorAll('.navbar-link').forEach(function(navbarLink){
  navbarLink.addEventListener('click', function(){
    navbarLink.nextElementSibling.classList.toggle('is-hidden-mobile');
  })
});
</script>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
          <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
          new Noty ({
              type: '<%= type %>',
              layout: 'topRight',
              timeout: '3000',
              theme: 'sunset',
              text: '<%= value %>'
          }).show();
        <% end %>
    </script>
<% end %>