config/routes.rb
Rails.application.routes.draw do

  get 'message/create'
  root 'pages#home'

  get 'pages/terms', to: 'pages#terms'
  get 'pages/privacy', to: 'pages#privacy'
  get 'pages/cookies', to: 'pages#cookies'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show', as: 'users'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/orders/:id', to: 'orders#show', as: "order_detail"
  get '/search', to: 'pages#search'
  get '/calendar', to: 'pages#calendar'
  get '/plans', to: 'pages#plans'
  get '/settings/payment', to: 'users#payment', as: 'settings_payment'
  get '/settings/payout', to: 'users#payout', as: 'settings_payout'
  get '/contents/:id/checkout/:pricing_type', to: 'contents#checkout', as: 'checkout'
  get '/earnings', to: 'users#earnings', as: 'earnings'
  get '/conversations', to: 'conversations#list', as: "conversations"
  get '/conversations/:id', to: 'conversations#show', as: "conversation_detail"

  post '/users/edit', to: 'users#update'
  post '/reviews', to: 'reviews#create'
  post '/settings/payment', to: 'users#update_payment', as: "update_payment"
  post '/settings/payout', to: 'users#update_payout', as: "update_payout"
  post '/users/withdraw', to: 'users#withdraw', as: 'withdraw'
  post 'messages', to: 'messages#create'
  post '/comments', to: 'comments#create'
  post '/subscribe', to: 'subscriptions#subscribe'
  post '/webhook', to: 'subscriptions#webhook'

  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'

  delete '/users/remove_subscription', to: 'users#remove_subscription', as: 'remove_subscription'

  mount ActionCable.server => '/cable'

  resources :contents do
    member do
      delete :delete_photo
      post :upload_photo
      post :update_content_status
    end
    resources :orders, only: [:create]
  end

  resources :pages do 
    collection do
      get :terms, :privacy, :cookies
    end
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names: {sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations', sessions: 'sessions'}

  devise_scope :user do
                get '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
                post '/users/auth/stripe_connect/callback' => 'omniauth_callbacks#stripe_connect'
              end

  resources :users, only: [:show] do
    member do
      post '/verify_phone' => 'users#verify_phone'
      patch '/update_phone' => 'users#update_phone'
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :content, required: false
    belongs_to :request, required: false

    belongs_to :buyer, class_name: "User"
    belongs_to :creator, class_name: "User"

    has_many :reviews, dependent: :destroy
    has_many :comments, dependent: :destroy

    enum status: [:inprogress, :completed]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    before_action :is_authorised, only: [:show]
    
    def create
        content = Content.friendly.find(params[:content_id])
        pricing = content.pricings.find_by(pricing_type: params[:pricing_type])

        if (pricing && !content.has_single_price) || (pricing && pricing.basic? && content.has_single_price)
            if intent(content, pricing)
                OrderMailer.with(buyer_user: current_user).order_buyer_email.deliver_now
                OrderMailer.with(creator_user: content.user).order_creator_email.deliver_now
                return redirect_to buying_orders_path
            end
        else
            flash[:alert] = "Price is incorrect"
        end

        return redirect_to request.referrer
    end

    def selling_orders
        @orders = current_user.selling_orders.order("created_at DESC")
    end

    def buying_orders
        @orders = current_user.buying_orders.order("created_at DESC")
    end

    def complete
        @order = Order.find(params[:id])

        if !@order.completed?
            if @order.completed!
                OrderMailer.with(order: @order).mark_as_complete_buyer_email.deliver_now
                OrderMailer.with(order: @order).mark_as_complete_creator_email.deliver_now
                flash[:notice] = "Saved..."
            else
                flash[:aler] = "Something went wrong..."
            end

            redirect_to request.referrer
        end
    end

    def show
        @order = Order.find(params[:id])
        @content = @order.content_id ? Content.find(@order.content_id) : nil
        # @request = @order.request_id ? Request.find(@order.request_id) : nil
        @comments = Comment.where(order_id: params[:id])
    end

    private

    def is_authorised
        redirect_to dashboard_path, 
            alert: "You don't have permission" unless Order.where("id = ? AND (creator_id = ? OR buyer_id = ?", 
                                                                    params[:id], current_user.id, current_user.id)
    end

    def intent(content, pricing)

        subscription = Subscription.find_by_user_id(current_user.id)
        if subscription.present? && subscription.success?
            plan = Stripe::Plan.retrieve(subscription.plan_id)
            rate =  plan.metadata.commission.to_f/100
        else
            rate = 20.0/100
        end

        amount = pricing.price * (rate + 1)

        order = content.orders.new
        order.due_date = Date.today() + pricing.delivery_time.days
        order.title = content.title
        order.creator_name = content.user.full_name
        order.creator_id = content.user.id
        order.buyer_name = current_user.full_name
        order.buyer_id = current_user.id
        order.amount = amount

        if params[:payment].blank?
            flash[:alert] = "No payment selected"
            return false
        # elsif params[:payment] == "system"
        #     if amount > current_user.wallet
        #         flash[:alert] = "Not enought money"
        #         return false
        #     else
        #         ActiveRecord::Base.transaction do
        #             current_user.update!(wallet: current_user.wallet - amount)
        #             content.user.update!(wallet: content.user.wallet + pricing.price)
        #             Transaction.create! status: Transaction.statuses[:approved],
        #                                 transaction_type: Transaction.transaction_types[:trans],
        #                                 source_type: Transaction.source_types[:system],
        #                                 buyer: current_user,
        #                                 creator: content.user,
        #                                 amount: amount,
        #                                 content: content
        #             order.save
        #         end
        #         flash[:notice] = "Your order is created successfully"
        #         return true
        #     end
        else
            # TODO: 
            # 1. find better way to handle Stripe Payment Intent API
            # 2. Move Stripe Payment Intent API logic to service


            payment_intent = Stripe::PaymentIntent.create({
                amount: (amount * 100).to_i,
                currency: 'usd',
                confirm: true,
                customer: current_user.stripe_id,
                :transfer_data => {
                    :amount => (pricing.price * 100).to_i,
                    :destination => content.user.merchant_id # Host's Stripe customer ID
                  }
            })

            if payment_intent.status == 'succeeded'
                ActiveRecord::Base.transaction do
                    # content.user.update!(wallet: content.user.wallet + pricing.price)
                    Transaction.create! status: Transaction.statuses[:approved],
                                        transaction_type: Transaction.transaction_types[:trans],
                                        source_type: Transaction.source_types[:stripe],
                                        buyer: current_user,
                                        creator: content.user,
                                        amount: amount,
                                        content: content
                    order.save
                end
                flash[:notice] = "Your order is created successfully"
                return true
            end
            flash[:alert] = "Invalid card"
            return false
        end

    rescue ActiveRecord::RecordInvalid
        flash[:alert] = "Something went wrong"
        return false
    end
end

app/views/orders/_comment.html.erb
<style>
.rounded-img-container {
  display: inline-block;
  width: 64px;
  height: 64px;
  border-radius: 50%;
  overflow: hidden;
}
.rounded-img {
  width: inherit;
  height: inherit;
  border-radius: inherit;
  
  object-fit: cover;
  object-position: center;
}
.content {
  font-family: "Nexa Regular", sans-serif;
}

</style>
<article class="media">

    <figure class="media-left">
        <div class="rounded-img-container">
            <%= image_tag avatar_url(comment.user), class: "rounded-img" %>
        </div>
    </figure>
    <div class="media-content">
        <div class="content">
            <p>
                <strong><%= comment.user.full_name %></strong>
                <small class="is-pulled-right"><%= time_ago_in_words(comment.created_at) %></small>
                <br>
                <%= comment.content %>
                <br>
            </p>
        </div>

        <% if comment.attachment_file.attached? %>
            <p>
                <%= link_to url_for(comment.attachment_file), 
                                class: "tag small is-warning m-t-20",  
                                download: "Attachment_#{comment.attachment_file.id}" do %>
                    <i class="fas fa-paperclip fa-lg p-r-5"></i> <%= comment.attachment_file.filename %>

                <% end %>
            </p>
        <% end %>
    </div>
</article>

app/views/orders/buying_orders.html.erb
<style>
@media only screen and (max-width: 800px) {
	
	/* Force table to not be like tables anymore */
	table, 
	thead, 
	tbody, 
	th, 
	td, 
	tr { 
		display: block; 
	}
 
	/* Hide table headers (but not display: none;, for accessibility) */
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
 
	tr { border: 1px solid #ccc; }
 
	td { 
		/* Behave  like a "row" */
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; 
		white-space: normal;
		text-align:left;
	}
 
	td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 45%; 
		padding-right: 10px; 
		white-space: nowrap;
		text-align:left;
		font-weight: bold;
	}
 
	/*
	Label the data
	*/
	td:before { content: attr(data-title); }
}

.title {
  font-family: "Nexa Bold", sans-serif;
}

.table{
    font-family: "Nexa Regular", sans-serif;
}

</style>

<% content_for(:html_title) { 'Manage Purchase History - Ceefuu' } %>
<section class="section">
    <div class="container">
        <p class="title">Purchase History</p>
    <div style="overflow-x:auto;">
        <table class="table is-striped is-hoverable is-fullwidth is-bordered">
            <thead>
                <tr>
                    <th class="numeric">Date</th>
                    <th class="numeric">Creator Name</th>
                    <th class="numeric">Order Details</th>
                    <th class="numeric">Due Date</th>
                    <th class="numeric">Amount</th>
                    <th class="numeric">Status</th>
                    <th class="numeric">Action</th>
                </tr>
            </thead>
            <tbody>
                <% if @orders.blank? %>
                  <tr>
                      <td colspan="7" class="has-text-centered"></td>
                  </tr>
                <% end %>
                <% @orders.each do |o| %>
                    <tr>
                        <td data-title="Date" class="has-text-right-mobile"><%= o.created_at.strftime('%d %b %Y') %></td>
                        <td data-title="Creator Name" class="has-text-right-mobile"><%= o.creator_name %></td>
                        <td data-title="Order Details" class="has-text-right-mobile">
                            <%= link_to 'View Details', order_detail_path(o), data: { turbolinks: true}  %>
                        </td>
                        <td data-title="Due Date" class="has-text-right-mobile"><%= o.due_date.strftime('%d %b %Y') %></td>
                        <td data-title="Amount" class="has-text-right-mobile"><%= number_to_currency(o.amount) %></td>
                        <td data-title="Status" class="has-text-right-mobile">
                            <span class="tag <%= 'is-warning' if o.inprogress? %> <%= 'is-black' if o.completed? %>">
                                <%= o.status.capitalize %>
                            </span>
                        </td>
                        <td class="has-text-right-mobile">
                            <% if !o.completed? %>
                                <%= link_to 'Mark Complete', complete_order_path(o), method: :put, class: "button is-small is-black #{'is-hidden' if o.completed?}" %>  
                            <% else %>
                                <a class="button is-small is-outlined is-success toggle-modal" aria-control="<%= o.id %>">Rating</a>

                                <div class="modal" id="<%= o.id %>">
                                    <div class="modal-background"></div>
                                    <div class="modal-content">
                                        <div class="box">
                                            <%= form_for Review.new do |f| %>
                                                <%= f.hidden_field :order_id, value: o.id %>
                                                <div class="field">
                                                    <div id="star_<%= o.id %>"></div>
                                                </div>
                                                <div class="field">
                                                    <%= f.text_area :review, class: "textarea" %>
                                                </div>
                                                <a class="toggle-modal button is-light" aria-control="<%= o.id %>">Cancel</a>
                                                <%= f.submit "Add Review", class: "button is-black" %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            <% end %>
                            
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
</div>
    </div>
</section>

<script>
    $('.toggle-modal').on('click', (e) => {
        e.stopPropagation();
        e.preventDefault();

        var order_id = e.target.getAttribute('aria-control');
        $('#star_' + order_id).raty({
            path: '/assets/raty-js/lib/images',
            scoreName: 'review[stars]',
            score: 1
        });
        $('star_' + order_id).raty('reload');
        $('#' + order_id).toggleClass('is-active');
    });
</script>

app/views/orders/selling_orders.html.erb
<style>
@media only screen and (max-width: 800px) {
	
	/* Force table to not be like tables anymore */
	table, 
	thead, 
	tbody, 
	th, 
	td, 
	tr { 
		display: block; 
	}
 
	/* Hide table headers (but not display: none;, for accessibility) */
	thead tr { 
		position: absolute;
		top: -9999px;
		left: -9999px;
	}
 
	tr { border: 1px solid #ccc; }
 
	td { 
		/* Behave  like a "row" */
		border: none;
		border-bottom: 1px solid #eee; 
		position: relative;
		padding-left: 50%; 
		white-space: normal;
		text-align:left;
	}
 
	td:before { 
		/* Now like a table header */
		position: absolute;
		/* Top/left values mimic padding */
		top: 6px;
		left: 6px;
		width: 45%; 
		padding-right: 10px; 
		white-space: nowrap;
		text-align:left;
		font-weight: bold;
	}
 
	/*
	Label the data
	*/
	td:before { content: attr(data-title); }
}
.title {
  font-family: "Nexa Bold", sans-serif;
}

.table{
    font-family: "Nexa Regular", sans-serif;
}
.is-size-7{
    font-family: "Nexa Regular", sans-serif;
}
</style>

<% content_for(:html_title) { 'Manage Selling History - Ceefuu' } %>
<section class="section">
    <div class="container">
        <p class="title">Selling History</p>
        <p class="is-size-7">*Total amount is inclusive of the service fee. The final payment will be the actual pricing of the content<p><br>
    <div>
        <table class="table is-striped is-hoverable is-fullwidth is-bordered">
            <thead>
                <tr>
                    <th class="numeric">Date</th>
                    <th class="numeric">Buyer Name</th>
                    <th class="numeric">Order Details</th>
                    <th class="numeric">Due Date</th>
                    <th class="numeric">Amount*</th>
                    <th class="numeric">Status</th>
                    <th class="numeric">Action</th>
                </tr>
            </thead>
            <tbody>
                <% if @orders.blank? %>
                  <tr>
                      <td colspan="6" class="has-text-centered"></td>
                  </tr>
                <% end %>
                <% @orders.each do |o| %>
                    <tr>
                        <td data-title="Date" class="has-text-right-mobile"><%= o.created_at.strftime('%d %b %Y') %></td>
                        <td data-title="Buyer Name" class="has-text-right-mobile"><%= o.buyer_name %></td>
                        <td data-title="Order Details" class="has-text-right-mobile">
                            <%= link_to 'View Details', order_detail_path(o), data: { turbolinks: true} %>
                        </td>
                        <td data-title="Due Date" class="has-text-right-mobile"><%= o.due_date.strftime('%d %b %Y') %></td>
                        <td data-title="Amount" class="has-text-right-mobile"><%= number_to_currency(o.amount) %></td>
                        <td data-title="Status" class="has-text-right-mobile">
                            <span class="tag <%= 'is-warning' if o.inprogress? %> <%= 'is-black' if o.completed? %>">
                                <%= o.status.capitalize %>
                            </span>
                        </td>
                        <td class="has-text-right-mobile">
                            <%= link_to 'Mark Complete', complete_order_path(o), method: :put, class: "button is-small is-black #{'is-hidden' if o.completed?}" %> 
                        </td> 
                    </tr>
                <% end %>
            </tbody>
        </table>
</div>
    </div>
</section>

app/views/orders/show.html.erb
<style>
.rounded-img-container {
  display: inline-block;
  width: 64px;
  height: 64px;
  border-radius: 50%;
  overflow: hidden;
}
.rounded-img {
  width: inherit;
  height: inherit;
  border-radius: inherit;
  
  object-fit: cover;
  object-position: center;
}
.menu-label {
  font-family: "Nexa Bold", sans-serif;
}
.file-label{
    font-family: "Nexa Bold", sans-serif;
}
.button{
    font-family: "Nexa Bold", sans-serif;
}
.card-content{
    font-family: "Nexa Bold", sans-serif;

}
}
</style>
<% content_for(:html_title) { 'Orders - Ceefuu' } %>
<section class="section" data-channel-subscribe="order" data-order-id="<%= @order.id %>">
    <div class="container">
        <div class="columns">

            <!-- LEFT SIDE -->
            <div class="column is-two-thirds">
                <p class="menu-label">
                    Your order history
                </p>
                <hr>
                <div id="comment-list">
                   <% @comments.each do |c| %>
                    <%= render 'orders/comment', comment: c %><br>
                   <% end %>
                </div>
                <hr>

                <article class="media">
                    <div class="media-content">
                        <%= form_with model: Comment.new, id: "new-comment" do |f| %>
                            <%= f.hidden_field :order_id, value: @order.id %>
                            <div class="field">
                                <%= f.text_area :content, class: "textarea", placeholder: "Type your comment or send your links" %>
                            </div>

                            <div class="field is-pulled-left">
                                <div class="file is-warning has-name">
                                    <label class="file-label">
                                        <%= f.file_field :attachment_file, class: "file-input" %>
                                        <span class="file-cta">
                                            <span class="file-label">Attachment</span>
                                        </span>
                                        <span class="file-name" id="file-name">No file selected</span>
                                    </label>
                                </div>
                            </div>

                            <div class="field is-pulled-right">
                                <%= f.submit "Send", class: "button is-black", data: { disable_with: false } %>                          
                            </div>
                        <% end %>
                    </div>
                </article>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="card">
                    <div class="card-image">                        
                        <figure class="image is-4by4">
                            <%= image_tag content_cover(@content) if @content %>
                            <%= image_tag 'icon_default_image.png' if @request %>
                        </figure>
                    </div>
                    <div class="card-content">
                        <p>
                            <strong><%= @order.title %></strong>
                            <strong class="title is-4 is-pulled-right has-text-success"></strong>
                        </p>
                        <br>
                        <small>
                            <p>Buyer: <%= @order.buyer_name %></p>
                            <br>
                            <p>Order ID: <%= @order.id %></p>
                            <br>
                            <p>Created at: <%= @order.created_at.strftime('%d, %b %Y') %></p>  
                        </small>                    
                    </div>                   
                </div>
            </div>

        </div>
    </div>
</section>

<script>
    $(document).ready(function() {
        var file = $('.file-input');
        file.change(function(e) {
            if (file[0].files.length > 0) {
                var attachment = file[0].files[0];
                $('.file-name').text(attachment.name + " (" + attachment.size + " bytes)");
            }
        })
    })
</script>